### PR TITLE
Fixed #522

### LINKED ISSUE #522: FocusNode instance is not created if not given
According to the comments of `focusNode` field of `widgets/editor.dart`, the `focusNode` can is optional and should be created by editor if is not given. But it's not implemented correctly and throws exception if you don't provide editor with a `FocusNode`.

## Steps to Reproduce

1. Create a `ZefyrField` or `ZefyrEditor` without setting `focusNode`
2. Run

## Logs

```
The following _CastError was thrown building ZefyrEditor(dirty, dependencies:
[_LocalizationsScope-[GlobalKey#14022], _InheritedTheme], state:
_ZefyrEditorState#d0f2e):
Null check operator used on a null value

When the exception was thrown, this was the stack:
#0      _ZefyrEditorState.build (package:zefyr/src/widgets/editor.dart:283:34)
```

### PR DESCRIPTION
**Pull request by Amir-P**

### CODE REVIEW

File: packages/zefyr/lib/src/widgets/editor.dart [hunk 1]
```diff
@@ -853,11 +860,11 @@ class RawEditorState extends EditorState
     }
 
     if (widget.focusNode != oldWidget.focusNode) {
-      oldWidget.focusNode.removeListener(_handleFocusChanged);
+      oldWidget.focusNode?.removeListener(_handleFocusChanged);
```
Comment (pulyaevskiy) [inline packages/zefyr/lib/src/widgets/editor.dart:863]: What if `widget.focusNode` is set, `oldWidget.focusNode` is null and we have an internal instance currently?

Our internal focusNode will not be cleaned up in this case, right?

I think I'd prefer to refactor this logic as well as `effectiveFocusNode` not rely on `_focusNode ?? FocusNode()` in `effectiveFocusNode`. Instead initialize focus not here in `didUpdateWidget`.

I feel like the way it works now is a bit fragile and can lead to unexpected issues which would be hard to track and fix.

WDYT?

**Review by pulyaevskiy — CHANGES_REQUESTED** [review]
This looks good overall. Just have one suggestion.

File: packages/zefyr/lib/src/widgets/editor.dart (hunk 1 above)
Comment (Amir-P) [reply packages/zefyr/lib/src/widgets/editor.dart:863]: You're right. I was thinking that our internal `focusNode` is going to be disposed when the state disposes but I missed the fact that the listener will still be called in that case.

File: packages/zefyr/lib/src/widgets/editor.dart [hunk 2]
```diff
@@ -853,11 +868,15 @@ class RawEditorState extends EditorState
...
+      if (_focusNode != null && widget.focusNode != null) {
+        _focusNode?.dispose();
+      }
```
Comment (pulyaevskiy) [inline packages/zefyr/lib/src/widgets/editor.dart:874]: This `if` statement is unnecessary I think. Also we still need to take care of the listener on the internal instance. This can be simplified as:

```dart
_focusNode?.removeListener(_handleFocusChanged);
_focusNode?.dispose();
  // below is not _strictly_ required, but I prefer to not leave any pointers to 
  // disposed objects around, and let the runtime garbage collect them.
_focusNode = null; 
```

File: packages/zefyr/lib/src/widgets/editor.dart [hunk 3]
```diff
@@ -495,7 +495,7 @@ class RawEditor extends StatefulWidget {
 
   //TODO: Make it optional and create an instance if it's null
```
Comment (pulyaevskiy) [inline packages/zefyr/lib/src/widgets/editor.dart:496]: This todo is addressed by this PR right?

File: packages/zefyr/lib/src/widgets/editor.dart [hunk 4]
```diff
@@ -832,6 +841,12 @@ class RawEditorState extends EditorState
         !widget.controller.selection.isCollapsed;
   }
 
+  void _createInternalFocusNodeIfRequired() {
```
Comment (pulyaevskiy) [inline packages/zefyr/lib/src/widgets/editor.dart:844]: nit: I usually use `IfNeeded` suffix instead of `IfRequired`. Would be nice to follow the pattern here as well for consistency.

**Review by pulyaevskiy — APPROVED** [review]
LGTM, just a few more nits. PTAL!

**Comment by Amir-P** [comment]
I've applied all your suggestions @pulyaevskiy

**Review by pulyaevskiy — APPROVED** [review]
LGTM, thanks!
